-- Elisa Nextgen DRA baseline schema
-- Portable SQL: runs on PostgreSQL (production) AND H2 (demo default).
-- NOTE: rewriting V1 in place is safe while no production DB has migrated yet;
-- after first production deploy, evolve schema via new V2+ scripts only.

CREATE TABLE dra_binding (
    "key"           VARCHAR(255) PRIMARY KEY,
    group_id        VARCHAR(255) NOT NULL,
    peer_id         VARCHAR(255) NOT NULL,
    origin_host     VARCHAR(255),
    origin_realm    VARCHAR(255),
    ingress_peer_id VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_dra_binding_expires_at ON dra_binding (expires_at);

CREATE TABLE route_config (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version    INT NOT NULL UNIQUE,
    payload    TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_log (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor     VARCHAR(255) NOT NULL,
    action    VARCHAR(255) NOT NULL,
    diff_json TEXT
);

CREATE INDEX idx_audit_log_ts ON audit_log (ts DESC);
