quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=dra
quarkus.datasource.password=dra
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dra

%prod.quarkus.flyway.migrate-at-start=true
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:dratest;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.flyway.migrate-at-start=false

dra.bindings.ttl-default-seconds=86400
dra.bindings.sweep-every-seconds=60
dra.bindings.sweep-batch-size=1000
dra.bindings.writebehind.batch-size=200
dra.bindings.writebehind.interval-millis=500
dra.tx.timeout-millis=5000
